version: '3'

services:
  api:
    ports:
      - "8000:8000"
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  publisher:
    build:
      context: .
      dockerfile: publisher.dockerfile
    volumes:
      - .:/app

  postgres:
    image: postgres:13.3-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
        - ./backend/database_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
