version: '3'

services:
  api:
    ports:
      - "8000:8000"
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns:
      - "8.8.8.8"

  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  publisher:
    build:
      context: .
      dockerfile: publisher.dockerfile
    volumes:
      - .:/app
    depends_on:
      - "mqtt-broker"

  postgres:
    image: postgres:13.3-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
        - ./sigeml/database_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2.3-alpine
    ports:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
